# Generated by Django 4.0.5 on 2022-12-12 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('comment', '0013_alter_blockeduser_id_alter_blockeduserhistory_id_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0007_articlemodel_is_special_alter_articlemodel_status'),
        ('account', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='CustomUser',
        ),
    ]
