# Generated by Django 4.1.1 on 2022-09-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categorymodel_alter_articlemodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='category',
            field=models.ManyToManyField(to='blog.categorymodel', verbose_name='دسته بندی'),
        ),
    ]
