# Generated by Django 4.1.1 on 2022-10-04 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_categorymodel_options_articlemodel_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='auther',
            new_name='author',
        ),
    ]
