# Generated by Django 4.0.5 on 2022-10-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_auther_articlemodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='مقاله ویژه '),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='status',
            field=models.CharField(choices=[('d', 'پیشنویس'), ('p', 'منتشر شده'), ('i', ' در حال بررسی'), ('b', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت'),
        ),
    ]
