# Generated by Django 4.0.5 on 2022-12-20 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_ipaddress_articlemodel_hits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='hits',
        ),
    ]
