# Generated by Django 4.0.5 on 2022-12-20 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_articlemodel_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleHits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='blog.ArticleHits', to='blog.ipaddress', verbose_name='بازدیدها'),
        ),
        migrations.AddField(
            model_name='articlehits',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.articlemodel'),
        ),
        migrations.AddField(
            model_name='articlehits',
            name='ip_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ipaddress'),
        ),
    ]
