# Generated by Django 4.0.5 on 2022-12-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_articlehits_articlemodel_hits_articlehits_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaddress',
            old_name='ip_Address',
            new_name='ip_address',
        ),
    ]
